Repository jthegedus/firebase-gcp-examples, pull requests merged in 2019-06, with the labels that each got.

#32 deprecated: rm older examples
  deprecated/fb-functions-compiled_code/README.md
  deprecated/fb-functions-compiled_code/babel-flow/.babelrc
  deprecated/fb-functions-compiled_code/babel-flow/.tool-versions
  deprecated/fb-functions-compiled_code/babel-flow/firebase.json
  deprecated/fb-functions-compiled_code/babel-flow/package.json
  deprecated/fb-functions-compiled_code/babel-flow/src/index.js
  deprecated/fb-functions-compiled_code/babel-flow/yarn.lock
  deprecated/fb-functions-compiled_code/babel/.babelrc
  deprecated/fb-functions-compiled_code/babel/.tool-versions
  deprecated/fb-functions-compiled_code/babel/firebase.json
  deprecated/fb-functions-compiled_code/babel/package.json
  deprecated/fb-functions-compiled_code/babel/src/index.js
  deprecated/fb-functions-compiled_code/babel/yarn.lock
  deprecated/fb-functions-compiled_code/parcel-flow/.tool-versions
  deprecated/fb-functions-compiled_code/parcel-flow/firebase.json
  deprecated/fb-functions-compiled_code/parcel-flow/package.json
  deprecated/fb-functions-compiled_code/parcel-flow/src/index.js
  deprecated/fb-functions-compiled_code/parcel-flow/yarn.lock
  deprecated/fb-functions-compiled_code/parcel-reasonml/.tool-versions
  deprecated/fb-functions-compiled_code/parcel-reasonml/bsconfig.json
  deprecated/fb-functions-compiled_code/parcel-reasonml/firebase.json
  deprecated/fb-functions-compiled_code/parcel-reasonml/package.json
  deprecated/fb-functions-compiled_code/parcel-reasonml/src/Main.bs.js
  deprecated/fb-functions-compiled_code/parcel-reasonml/src/Main.re
  deprecated/fb-functions-compiled_code/parcel-reasonml/src/index.js
  deprecated/fb-functions-compiled_code/parcel-reasonml/yarn.lock
  deprecated/fb-functions-compiled_code/parcel-typescript/.tool-versions
  deprecated/fb-functions-compiled_code/parcel-typescript/firebase.json
  deprecated/fb-functions-compiled_code/parcel-typescript/package.json
  deprecated/fb-functions-compiled_code/parcel-typescript/src/index.ts
  deprecated/fb-functions-compiled_code/parcel-typescript/tsconfig.json
  deprecated/fb-functions-compiled_code/parcel-typescript/yarn.lock
  deprecated/fb-functions-compiled_code/typescript/.tool-versions
  deprecated/fb-functions-compiled_code/typescript/firebase.json
  deprecated/fb-functions-compiled_code/typescript/package.json
  deprecated/fb-functions-compiled_code/typescript/src/index.ts
  deprecated/fb-functions-compiled_code/typescript/tsconfig.json
  deprecated/fb-functions-compiled_code/typescript/yarn.lock
  deprecated/fb-functions-express/README.md
  deprecated/fb-functions-express/firebase.json
  deprecated/fb-functions-express/package.json
  deprecated/fb-functions-express/src/functions/index.js
  deprecated/fb-functions-express/yarn.lock
  deprecated/fb-namespaced_packages/.gitignore
  deprecated/fb-namespaced_packages/README.md
  deprecated/fb-namespaced_packages/package.json
  deprecated/fb-namespaced_packages/src/next.config.js
  deprecated/fb-namespaced_packages/src/pages/about.js
  deprecated/fb-namespaced_packages/src/pages/contact.js
  deprecated/fb-namespaced_packages/src/pages/index.js
  deprecated/fb-namespaced_packages/yarn.lock
Labels: dependencies

#40 nuxtjs example
  functions-nuxtjs/README.md
  functions-nuxtjs/firebase.json
  functions-nuxtjs/package.json
  functions-nuxtjs/public/favicon-16x16.png
  functions-nuxtjs/public/favicon-32x32.png
  functions-nuxtjs/public/favicon-96x96.png
  functions-nuxtjs/public/favicon.ico
  functions-nuxtjs/public/placeholder.html
  functions-nuxtjs/src/client/components/Header.vue
  functions-nuxtjs/src/client/layouts/default.vue
  functions-nuxtjs/src/client/nuxt.config.js
  functions-nuxtjs/src/client/pages/about.vue
  functions-nuxtjs/src/client/pages/index.vue
  functions-nuxtjs/src/server/.babelrc
  functions-nuxtjs/src/server/index.js
  functions-nuxtjs/yarn.lock
Labels: enhancement

#43 nuxtjs: add to repo index table
  README.md
Labels: enhancement

#46 nextjs: serve working OOB by bumping firebase-tools@7.0.0 to use functions-framework
  functions-nextjs/README.md
  functions-nextjs/package.json
  functions-nextjs/yarn.lock
Labels: bug, dependencies, enhancement
